# Generated by Django 6.1.1 on 2026-09-16 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('committed_vehicles', models.PositiveIntegerField(default=1)),
                ('agreed_rate_per_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('agreed_monthly_fixed', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=200)),
                ('document_type', models.CharField(default='SIGNED_AGREEMENT', max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractTrip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('attributed_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_number', models.CharField(db_index=True, max_length=100)),
                ('quoted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('submission_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Proposal'), ('SUBMITTED', 'Submitted'), ('NEGOTIATION', 'In Negotiation'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=30)),
                ('commercial_terms', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tender_number', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('submission_deadline', models.DateTimeField(db_index=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Open for Bidding'), ('BID_SUBMITTED', 'Bid Submitted'), ('EVALUATION', 'Under Evaluation'), ('AWARDED', 'Awarded / Won'), ('LOST', 'Lost')], db_index=True, default='OPEN', max_length=30)),
                ('scope_of_work', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('total_contract_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('minimum_monthly_commitment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_terms_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Legal/Finance Approval'), ('ACTIVE', 'Active Execution'), ('RENEWAL_DUE', 'Renewal Due'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], db_index=True, default='DRAFT', max_length=30)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
