# Generated by Django 6.1.1 on 2026-09-16 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('crm', '0001_initial'),
        ('fleet', '0001_initial'),
        ('tenants', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contractallocation',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractallocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contractallocation',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehiclecategory'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contracttrip',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_trips', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contracttrip',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contracttrip',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contracttrip',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_attribution', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contract',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.proposal'),
        ),
        migrations.AddField(
            model_name='tender',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tender',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='contracts.tender'),
        ),
        migrations.AddIndex(
            model_name='contractallocation',
            index=models.Index(fields=['tenant', 'created_at'], name='contracts_c_tenant__7faee4_idx'),
        ),
        migrations.AddIndex(
            model_name='contractallocation',
            index=models.Index(fields=['tenant', 'is_deleted'], name='contracts_c_tenant__60c092_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdocument',
            index=models.Index(fields=['tenant', 'created_at'], name='contracts_c_tenant__3b0622_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdocument',
            index=models.Index(fields=['tenant', 'is_deleted'], name='contracts_c_tenant__1cacc1_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttrip',
            index=models.Index(fields=['tenant', 'created_at'], name='contracts_c_tenant__ac918b_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttrip',
            index=models.Index(fields=['tenant', 'is_deleted'], name='contracts_c_tenant__4ddfb7_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'status'], name='contracts_c_tenant__8ef07c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'end_date'], name='contracts_c_tenant__2ba62c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('tenant', 'contract_number')},
        ),
        migrations.AlterUniqueTogether(
            name='tender',
            unique_together={('tenant', 'tender_number')},
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('tenant', 'proposal_number')},
        ),
    ]
