# Generated by Django 6.1.1 on 2026-09-16 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(db_index=True, max_length=50)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cargo_type', models.CharField(max_length=100)),
                ('cargo_weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('commercial_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('ALLOCATED', 'Allocated to Trip'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='crm.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('standard_distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('toll_points_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_number', models.CharField(db_index=True, max_length=50)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('start_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('end_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('freight_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('detention_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('DISPATCHED', 'Dispatched'), ('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BILLING_READY', 'Billing Ready'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='crm.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.driver')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.route')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(choices=[('FUEL', 'Fuel Refill'), ('TOLL', 'Highway Toll'), ('DRIVER', 'Driver Allowance / Daily Batta'), ('PARKING', 'Parking Fee'), ('OTHER', 'Other Incidental Expense')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('receipt_file', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status'], name='trips_booki_tenant__41efa3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'scheduled_date'], name='trips_booki_tenant__b15540_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('tenant', 'booking_number')},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['tenant', 'status'], name='trips_trip_tenant__3c09fc_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['tenant', 'actual_start'], name='trips_trip_tenant__38ea62_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['tenant', 'customer'], name='trips_trip_tenant__bc2896_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('tenant', 'trip_number')},
        ),
        migrations.AddIndex(
            model_name='tripexpense',
            index=models.Index(fields=['tenant', 'expense_type'], name='trips_tripe_tenant__df361e_idx'),
        ),
    ]
