# Generated by Django 6.1.1 on 2026-09-16 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(db_index=True, max_length=100)),
                ('incident_date', models.DateField(db_index=True)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Claim Submitted'), ('UNDER_SURVEY', 'Under Surveyor Assessment'), ('APPROVED', 'Approved by Insurer'), ('SETTLED', 'Funds Disbursed & Settled'), ('REJECTED', 'Claim Rejected')], db_index=True, default='SUBMITTED', max_length=30)),
                ('surveyor_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(db_index=True, max_length=100)),
                ('provider_name', models.CharField(max_length=200)),
                ('policy_type', models.CharField(choices=[('COMPREHENSIVE', 'Comprehensive Commercial Fleet'), ('THIRD_PARTY', 'Third Party Liability'), ('CARGO', 'Marine & Cargo Transit'), ('HEALTH', 'Group Driver & Employee Health')], default='COMPREHENSIVE', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(db_index=True)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(db_index=True, default='ACTIVE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regulation_name', models.CharField(max_length=200)),
                ('authority', models.CharField(max_length=150)),
                ('compliance_status', models.CharField(default='COMPLIANT', max_length=30)),
                ('audit_date', models.DateField()),
                ('next_due_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
