# Generated by Django 6.1.1 on 2026-09-16 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_initial'),
        ('insurance', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policies', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.insurancepolicy'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='compliancerecord',
            index=models.Index(fields=['tenant', 'created_at'], name='insurance_c_tenant__731021_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancerecord',
            index=models.Index(fields=['tenant', 'is_deleted'], name='insurance_c_tenant__bef478_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['tenant', 'end_date'], name='insurance_i_tenant__0d98a4_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['tenant', 'status'], name='insurance_i_tenant__8c1d04_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['tenant', 'created_at'], name='insurance_i_tenant__c0c206_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['tenant', 'is_deleted'], name='insurance_i_tenant__9e0e59_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['tenant', 'created_at'], name='insurance_l_tenant__71a9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['tenant', 'is_deleted'], name='insurance_l_tenant__547d84_idx'),
        ),
    ]
