# Generated by Django 6.1.1 on 2026-09-16 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_initial'),
        ('crm', '0002_initial'),
        ('drivers', '0002_initial'),
        ('finance', '0001_initial'),
        ('fleet', '0001_initial'),
        ('tenants', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_purchases', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_transactions', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tolltransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tolltransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tolltransaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toll_transactions', to='fleet.vehicle'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['tenant', 'created_at'], name='finance_col_tenant__2aa21b_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['tenant', 'is_deleted'], name='finance_col_tenant__47f4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'expense_date'], name='finance_exp_tenant__3c8047_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'category'], name='finance_exp_tenant__00f147_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['tenant', 'created_at'], name='finance_fue_tenant__5610ad_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['tenant', 'is_deleted'], name='finance_fue_tenant__a42828_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='finance_inv_tenant__e82747_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'due_date'], name='finance_inv_tenant__14e836_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'customer'], name='finance_inv_tenant__0efda2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('tenant', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['tenant', 'created_at'], name='finance_inv_tenant__c68efb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['tenant', 'is_deleted'], name='finance_inv_tenant__92df30_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='finance_pay_tenant__c6da43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('tenant', 'idempotency_key')},
        ),
        migrations.AddIndex(
            model_name='tolltransaction',
            index=models.Index(fields=['tenant', 'created_at'], name='finance_tol_tenant__729a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='tolltransaction',
            index=models.Index(fields=['tenant', 'is_deleted'], name='finance_tol_tenant__1f2417_idx'),
        ),
    ]
