# Generated by Django 6.1.1 on 2026-09-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_entitlements', to='subscriptions.feature'),
        ),
        migrations.AddField(
            model_name='tenantfeature',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_features', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='packagefeature',
            unique_together={('package', 'feature')},
        ),
        migrations.AddIndex(
            model_name='tenantfeature',
            index=models.Index(fields=['tenant', 'is_enabled'], name='subscriptio_tenant__3b302b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantfeature',
            unique_together={('tenant', 'feature')},
        ),
    ]
