# Generated by Django 6.1.1 on 2026-09-16 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFeatureOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, help_text='True to grant/unlock, False to explicitly revoke')),
                ('reason', models.TextField(blank=True, help_text='Operational rationale for custom feature override')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date for temporary features', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='subscriptions.feature')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'enabled'], name='subscriptio_tenant__d4c5e3_idx'), models.Index(fields=['tenant', 'expires_at'], name='subscriptio_tenant__e9f010_idx')],
                'unique_together': {('tenant', 'feature')},
            },
        ),
    ]
