# Generated by Django 6.1.1 on 2026-09-16 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '__first__'),
        ('finance', '0002_initial'),
        ('tenants', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepart',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ConsolidationGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_code', models.CharField(db_index=True, max_length=50)),
                ('destination_zone', models.CharField(db_index=True, max_length=150)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('total_parcels', models.PositiveIntegerField(default=0)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open for Inbound Manifests'), ('SEALED', 'Sealed for Transit'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered and Broken Down')], db_index=True, default='OPEN', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidations', to='courier.hub')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_groups', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-date_to'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidatedShipmentItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_reference', models.CharField(blank=True, max_length=100)),
                ('parcel_count', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidation_items', to='courier.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.consolidationgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrossDockOperation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cross_dock_number', models.CharField(db_index=True, max_length=50)),
                ('source_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('inbound_carrier', models.CharField(blank=True, max_length=150)),
                ('outbound_carrier', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('INBOUND_RECEIVED', 'Inbound Cargo Received'), ('SORTING', 'Sortation in Cross-Dock Bay'), ('CONSOLIDATED', 'Consolidated to Outbound Unit'), ('OUTBOUND_DISPATCHED', 'Dispatched to Destination'), ('COMPLETED', 'Cross-Dock Transfer Completed')], db_index=True, default='INBOUND_RECEIVED', max_length=30)),
                ('inbound_time', models.DateTimeField(auto_now_add=True)),
                ('outbound_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_dock_operations', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-inbound_time'],
            },
        ),
        migrations.CreateModel(
            name='CrossDockShipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('parcel_count', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='TRANSFERRED', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('cross_dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='warehouse.crossdockoperation')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_dock_movements', to='courier.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_number', models.CharField(db_index=True, max_length=50)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming Shipment to Warehouse'), ('OUTGOING', 'Outgoing Dispatch from Warehouse'), ('EXCHANGE', 'Warehouse Inter-Facility Exchange')], default='INCOMING', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Arrival / Schedule'), ('RECEIVED', 'Received at Warehouse Bay'), ('STAGED', 'Staged for Inspection / Sort'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('expected_time', models.DateTimeField(blank=True, null=True)),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_deliveries', to='finance.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_deliveries', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='consolidationgroup',
            index=models.Index(fields=['tenant', 'status'], name='warehouse_c_tenant__7e60a2_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidationgroup',
            index=models.Index(fields=['tenant', 'destination_zone'], name='warehouse_c_tenant__c4f6f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consolidationgroup',
            unique_together={('tenant', 'group_code')},
        ),
        migrations.AddIndex(
            model_name='consolidatedshipmentitem',
            index=models.Index(fields=['tenant', 'created_at'], name='warehouse_c_tenant__2ee38c_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidatedshipmentitem',
            index=models.Index(fields=['tenant', 'is_deleted'], name='warehouse_c_tenant__ada9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='crossdockoperation',
            index=models.Index(fields=['tenant', 'status'], name='warehouse_c_tenant__6cec4d_idx'),
        ),
        migrations.AddIndex(
            model_name='crossdockoperation',
            index=models.Index(fields=['tenant', 'warehouse'], name='warehouse_c_tenant__81c794_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crossdockoperation',
            unique_together={('tenant', 'cross_dock_number')},
        ),
        migrations.AddIndex(
            model_name='crossdockshipment',
            index=models.Index(fields=['tenant', 'created_at'], name='warehouse_c_tenant__6be1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='crossdockshipment',
            index=models.Index(fields=['tenant', 'is_deleted'], name='warehouse_c_tenant__718bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousedelivery',
            index=models.Index(fields=['tenant', 'warehouse', 'status'], name='warehouse_w_tenant__a619b2_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousedelivery',
            index=models.Index(fields=['tenant', 'delivery_number'], name='warehouse_w_tenant__652f79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousedelivery',
            unique_together={('tenant', 'delivery_number')},
        ),
    ]
