# Generated by Django 6.1.1 on 2026-09-16 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaignmetric',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='campaignmetric',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignmetric',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'created_at'], name='marketing_c_tenant__7672b6_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'is_deleted'], name='marketing_c_tenant__d9783a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmetric',
            index=models.Index(fields=['tenant', 'created_at'], name='marketing_c_tenant__73b867_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmetric',
            index=models.Index(fields=['tenant', 'is_deleted'], name='marketing_c_tenant__23a1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['tenant', 'created_at'], name='marketing_l_tenant__c9082c_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['tenant', 'is_deleted'], name='marketing_l_tenant__4330a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together={('tenant', 'promo_code')},
        ),
    ]
