# Generated by Django 6.1.1 on 2026-09-16 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='driver',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_drivers', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverassignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='driverassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='driverincident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverincident',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverincident',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='driverincident',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_incidents', to='fleet.vehicle'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['tenant', 'status'], name='drivers_dri_tenant__e82dae_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['tenant', 'license_expiry'], name='drivers_dri_tenant__714bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['tenant', 'license_number'], name='drivers_dri_tenant__12ac10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('tenant', 'license_number')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['tenant', 'date'], name='drivers_att_tenant__03e6eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('tenant', 'driver', 'date')},
        ),
        migrations.AddIndex(
            model_name='driverassignment',
            index=models.Index(fields=['tenant', 'is_active'], name='drivers_dri_tenant__71ad60_idx'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['tenant', 'expiry_date'], name='drivers_dri_tenant__33e2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='driverincident',
            index=models.Index(fields=['tenant', 'incident_date'], name='drivers_dri_tenant__ef5712_idx'),
        ),
        migrations.AddIndex(
            model_name='driverincident',
            index=models.Index(fields=['tenant', 'severity'], name='drivers_dri_tenant__b58274_idx'),
        ),
    ]
