# Generated by Django 6.1.1 on 2026-09-16 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_initial'),
        ('fleet', '0003_alter_vehicle_options'),
        ('tenants', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleOrganization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_type', models.CharField(choices=[('SCHOOL', 'School / Academic Institution'), ('CORPORATE', 'Corporate / Enterprise Employer')], default='CORPORATE', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('contact_person', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PassengerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_type', models.CharField(choices=[('STUDENT', 'Student'), ('EMPLOYEE', 'Corporate Employee')], default='EMPLOYEE', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(db_index=True, help_text='Roll number or employee badge ID', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='shuttle.shuttleorganization')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ShuttleRoute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=150)),
                ('route_code', models.CharField(db_index=True, max_length=50)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound (Pickup to Campus/Office)'), ('OUTBOUND', 'Outbound (Drop from Campus/Office)'), ('ROUND_TRIP', 'Round Trip Loop')], default='INBOUND', max_length=20)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('base_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shuttle_routes', to='trips.route')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('default_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_shuttle_routes', to='drivers.driver')),
                ('default_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_shuttle_routes', to='fleet.vehicle')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='shuttle.shuttleorganization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['route_code'],
            },
        ),
        migrations.CreateModel(
            name='ShuttleAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(blank=True, max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='shuttle.passengerprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('shuttle_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_assignments', to='shuttle.shuttleroute')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ShuttleSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(default='WEEKDAYS', help_text='MON, TUE, WED, THU, FRI, WEEKDAYS, or ALL', max_length=20)),
                ('departure_time', models.TimeField()),
                ('estimated_arrival_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
                ('shuttle_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='shuttle.shuttleroute')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='ShuttleStop',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=150)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('scheduled_offset_minutes', models.IntegerField(default=0, help_text='Minutes offset from trip start time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('shuttle_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='shuttle.shuttleroute')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='dropoff_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_passengers', to='shuttle.shuttlestop'),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='pickup_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_passengers', to='shuttle.shuttlestop'),
        ),
        migrations.CreateModel(
            name='ShuttleTrip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_number', models.CharField(db_index=True, max_length=50)),
                ('trip_date', models.DateField(db_index=True)),
                ('scheduled_start', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DISPATCHED', 'Dispatched'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shuttle_trips', to='drivers.driver')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shuttle.shuttleschedule')),
                ('shuttle_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_trips', to='shuttle.shuttleroute')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shuttle_trips', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-trip_date', '-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='ShuttleAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('BOARDED', 'Boarded Shuttle'), ('ALIGHTED', 'Alighted Safely'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused Absence')], default='BOARDED', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_history', to='shuttle.passengerprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shuttle_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shuttle.shuttlestop')),
                ('shuttle_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='shuttle.shuttletrip')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='shuttleorganization',
            index=models.Index(fields=['tenant', 'code'], name='shuttle_shu_tenant__fd623b_idx'),
        ),
        migrations.AddIndex(
            model_name='shuttleorganization',
            index=models.Index(fields=['tenant', 'org_type'], name='shuttle_shu_tenant__f6d0fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shuttleorganization',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='shuttleroute',
            index=models.Index(fields=['tenant', 'organization'], name='shuttle_shu_tenant__9a9319_idx'),
        ),
        migrations.AddIndex(
            model_name='shuttleroute',
            index=models.Index(fields=['tenant', 'route_code'], name='shuttle_shu_tenant__f39299_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shuttleroute',
            unique_together={('tenant', 'route_code')},
        ),
        migrations.AddIndex(
            model_name='shuttleassignment',
            index=models.Index(fields=['tenant', 'passenger'], name='shuttle_shu_tenant__b8c5e0_idx'),
        ),
        migrations.AddIndex(
            model_name='shuttleassignment',
            index=models.Index(fields=['tenant', 'shuttle_route'], name='shuttle_shu_tenant__54bfa4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shuttlestop',
            unique_together={('shuttle_route', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='passengerprofile',
            index=models.Index(fields=['tenant', 'id_number'], name='shuttle_pas_tenant__ed78eb_idx'),
        ),
        migrations.AddIndex(
            model_name='passengerprofile',
            index=models.Index(fields=['tenant', 'organization'], name='shuttle_pas_tenant__8e9722_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='passengerprofile',
            unique_together={('tenant', 'organization', 'id_number')},
        ),
        migrations.AddIndex(
            model_name='shuttletrip',
            index=models.Index(fields=['tenant', 'trip_date', 'status'], name='shuttle_shu_tenant__d8362d_idx'),
        ),
        migrations.AddIndex(
            model_name='shuttletrip',
            index=models.Index(fields=['tenant', 'shuttle_route'], name='shuttle_shu_tenant__141b74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shuttletrip',
            unique_together={('tenant', 'trip_number')},
        ),
        migrations.AddIndex(
            model_name='shuttleattendance',
            index=models.Index(fields=['tenant', 'shuttle_trip', 'status'], name='shuttle_shu_tenant__e41059_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shuttleattendance',
            unique_together={('shuttle_trip', 'passenger')},
        ),
    ]
