from rest_framework.renderers import JSONRenderer


class StandardResponseRenderer(JSONRenderer):
    """
    Standard JSON Response Renderer for OmniCore.
    Formats successful responses consistently with:
    - Single object / action: { "success": true, "message": "...", "data": {...} }
    - Paginated collection: { "success": true, "data": [...], "pagination": { "count": ..., "next": ..., "previous": ... } }
    Error responses generated by custom_exception_handler are already structured and passed through cleanly.
    """
    def render(self, data, accepted_media_type=None, renderer_context=None):
        response = renderer_context.get('response') if renderer_context else None
        
        # Don't alter file downloads, documentation schemas, or binary data
        if response and (response.status_code == 204 or getattr(response, 'streaming', False)):
            return super().render(data, accepted_media_type, renderer_context)

        # Check if already standardized (errors or custom payloads)
        if isinstance(data, dict) and 'success' in data:
            return super().render(data, accepted_media_type, renderer_context)

        # Check for paginated response
        if isinstance(data, dict) and 'results' in data and 'count' in data:
            results = data.get('results')
            pagination = {k: v for k, v in data.items() if k != 'results'}
            formatted_data = {
                'success': True,
                'data': results,
                'pagination': pagination
            }
            if response is not None:
                response.data = formatted_data
            return super().render(formatted_data, accepted_media_type, renderer_context)

        # Standard non-paginated payload
        formatted_data = {
            'success': True,
            'message': 'Operation successful.',
            'data': data
        }
        if response is not None:
            response.data = formatted_data
        return super().render(formatted_data, accepted_media_type, renderer_context)
