# Generated by Django 6.1.1 on 2026-09-16 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_from', models.DateTimeField()),
                ('assigned_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Vehicle Categories',
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('REGISTRATION', 'Registration Certificate (RC)'), ('INSURANCE', 'Insurance Policy'), ('FITNESS', 'Fitness Certificate'), ('ROAD_TAX', 'Road Tax Receipt'), ('PERMIT', 'National / State Transport Permit'), ('POLLUTION', 'Pollution Under Control (PUC)'), ('OTHER', 'Other Compliance Document')], max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('file_path', models.CharField(blank=True, help_text='S3 tenant-scoped storage path', max_length=500)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('PENDING_RENEWAL', 'Pending Renewal')], db_index=True, default='VALID', max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(db_index=True, max_length=50)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('vin_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('MAINTENANCE', 'In Maintenance'), ('INACTIVE', 'Inactive')], db_index=True, default='AVAILABLE', max_length=30)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available for Dispatch'), ('ASSIGNED', 'Assigned to Active Trip'), ('UNDER_INSPECTION', 'Under Inspection'), ('OUT_OF_SERVICE', 'Out of Service')], db_index=True, default='AVAILABLE', max_length=30)),
                ('ownership', models.CharField(choices=[('OWNED', 'Owned'), ('LEASED', 'Leased'), ('RENTED', 'Rented'), ('ATTACHED', 'Attached / Partner Fleet')], default='OWNED', max_length=30)),
                ('odometer', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fuel_type', models.CharField(default='DIESEL', max_length=50)),
                ('payload_capacity_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
