# Generated by Django 6.1.1 on 2026-09-16 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VEHICLE_DOCUMENT_EXPIRY', 'Vehicle Document Expiry Alert'), ('DRIVER_LICENSE_EXPIRY', 'Driver License Expiry Alert'), ('INSURANCE_RENEWAL', 'Insurance Renewal Notice'), ('MAINTENANCE_DUE', 'Vehicle Maintenance Due'), ('CONTRACT_EXPIRY', 'Contract Expiry Notice'), ('LOW_INVENTORY', 'Low Inventory / Reorder Alert'), ('PAYMENT_DUE', 'Invoice Payment Due / Overdue'), ('TRIP_ASSIGNMENT', 'New Trip Assignment'), ('TRIP_CHANGE', 'Trip Status / Schedule Change'), ('APPROVAL_REQUEST', 'Approval Request')], db_index=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
